OUTPUTDIR        ?= build

# --------------------------
#  Build & Clean
# --------------------------
.PHONY: all
all: 
	@echo "do nothing"

.PHONY: build
build:
	@bash scripts/cross-on-docker

.PHONY: archive
archive: 
	@bash scripts/archive-on-docker $(OUTPUTDIR)

.PHONY: release
release: 
	@bash scripts/release-on-docker $(OUTPUTDIR)

.PHONY: build-and-release
build-and-release: clean build archive release

.PHONY: clean
clean:
	@$(RM) -r $(OUTPUTDIR)

