#!/bin/bash

set -eu -o pipefail

source scripts/common

# usage: archive OUTPUTDIR 
OUTPUTDIR=$1
# optional files to be archived
ARCHIVE_MISC="LICENSE README.md"
ARCHIVE_DOC="document"

# setting for src. Assumed that all of these are under $OUTPUTDIR
ARCHIVE_SRC_LINUX=`find ${OUTPUTDIR} -name "erago*_linux_*"   -a -not -name "*.tar.gz"  | head -n 1 | xargs basename`
#ARCHIVE_SRC_DARWIN=`find ${OUTPUTDIR} -name "erago*_darwin_*"  -a -not -name "*.tar.gz"  | head -n 1 | xargs basename`
ARCHIVE_SRC_DARWIN="" # empty
ARCHIVE_SRC_WINDOWS=`find ${OUTPUTDIR} -name "erago*_windows_*.exe" | head -n 1 | xargs basename`
ARCHIVE_SRC_ANDROID=`find ${OUTPUTDIR} -name "erago*_android_*.aar" | head -n 1 | xargs basename`
ARCHIVE_SRC_DOC=$ARCHIVE_DOC
ARCHIVE_SRC_CREDITS_DESKTOP="CREDITS_list_desktop"
ARCHIVE_SRC_CREDITS_MOBILE="CREDITS_list_mobile"

# setting for dst

# we extract version from output of built binary.
VERSION=`${OUTPUTDIR}/${ARCHIVE_SRC_LINUX} -version 2>/dev/null`
ARCHIVE_DIR=`absolute_archive_path ${OUTPUTDIR} ${VERSION}`

ARCHIVE_DST_LINUX=${ARCHIVE_DIR}/${ARCHIVE_SRC_LINUX}.tar.gz
ARCHIVE_DST_DARWIN=${ARCHIVE_DIR}/${ARCHIVE_SRC_DARWIN}.tar.gz
ARCHIVE_DST_WINDOWS=${ARCHIVE_DIR}/${ARCHIVE_SRC_WINDOWS//.exe/.zip}
ARCHIVE_DST_ANDROID=${ARCHIVE_DIR}/${ARCHIVE_SRC_ANDROID//.aar/.zip}
ARCHIVE_DST_DOC=${ARCHIVE_DIR}/document.zip

# -----------------------
# do packing
# -----------------------
set -x
mkdir -p ${ARCHIVE_DIR} 
cp -r ${ARCHIVE_MISC} ${OUTPUTDIR} # to align every archive source are under OUTPUTDIR
pushd ${OUTPUTDIR} 

if [ -f "${ARCHIVE_SRC_LINUX}" ]; then
  : "packing for linux..."
  PKG_DIR_BASE=$ARCHIVE_SRC_LINUX
  mkdir -p tmp/${PKG_DIR_BASE}
  cp -t ./tmp/${PKG_DIR_BASE}/ ${ARCHIVE_SRC_LINUX} ${ARCHIVE_MISC} 
  cp ${ARCHIVE_SRC_CREDITS_DESKTOP} ./tmp/${PKG_DIR_BASE}/CREDITS 
  pushd tmp
  tar zcf ${ARCHIVE_DST_LINUX} ${PKG_DIR_BASE}/*
  popd
  rm -rf tmp
fi
if [ -f "${ARCHIVE_SRC_DARWIN}" ]; then
  : "packing for darwin..."
  PKG_DIR_BASE=$ARCHIVE_SRC_DARWIN
  mkdir -p tmp/${PKG_DIR_BASE}
  cp -t ./tmp/${PKG_DIR_BASE}/ ${ARCHIVE_SRC_DARWIN} ${ARCHIVE_MISC} 
  cp ${ARCHIVE_SRC_CREDITS_DESKTOP} ./tmp/${PKG_DIR_BASE}/CREDITS 
  pushd tmp
  tar zcf ${ARCHIVE_DST_DARWIN} ${PKG_DIR_BASE}/*
  popd
  rm -rf tmp
fi
if [ -f "${ARCHIVE_SRC_WINDOWS}" ]; then
  : "packing for windows..."
  PKG_DIR_BASE=${ARCHIVE_SRC_WINDOWS//.exe/}
  mkdir -p tmp/${PKG_DIR_BASE}
  cp -t ./tmp/${PKG_DIR_BASE}/ ${ARCHIVE_SRC_WINDOWS} ${ARCHIVE_MISC} 
  cp ${ARCHIVE_SRC_CREDITS_DESKTOP} ./tmp/${PKG_DIR_BASE}/CREDITS 
  pushd tmp
  zip -T ${ARCHIVE_DST_WINDOWS} ${PKG_DIR_BASE}/*
  popd
  rm -rf tmp
fi
if [ -f "${ARCHIVE_SRC_ANDROID}" ]; then
  : "packing for android library..."
  PKG_DIR_BASE=${ARCHIVE_SRC_ANDROID//.aar/}
  mkdir -p tmp/${PKG_DIR_BASE}
  cp -t ./tmp/${PKG_DIR_BASE}/ ${ARCHIVE_SRC_ANDROID} ${ARCHIVE_MISC}
  cp ${ARCHIVE_SRC_CREDITS_MOBILE} ./tmp/${PKG_DIR_BASE}/CREDITS
  pushd tmp
  zip -T ${ARCHIVE_DST_ANDROID} ${PKG_DIR_BASE}/*
  popd
  rm -rf tmp
fi
if [ -d "${ARCHIVE_SRC_DOC}" ]; then
  : "packing for document..."
  # document is already direcotry, so not need create pkg directory and just do zip.
  zip -Tr ${ARCHIVE_DST_DOC} ${ARCHIVE_SRC_DOC}/* 
fi

popd # return top 
