#!/bin/bash

set -eu -o pipefail

source scripts/common

# usage: archive OUTPUTDIR 
OUTPUTDIR=$1
# optional files to be archived
ARCHIVE_MISC="LICENSE README.md"

# setting for src 
ARCHIVE_SRC_LINUX=`find ${OUTPUTDIR} -name "erago*_linux_*"   -a -not -name "*.tar.gz"  | head -n 1 | xargs basename`
#ARCHIVE_SRC_DARWIN=`find ${OUTPUTDIR} -name "erago*_darwin_*"  -a -not -name "*.tar.gz"  | head -n 1 | xargs basename`
ARCHIVE_SRC_DARWIN="" # empty
ARCHIVE_SRC_WINDOWS=`find ${OUTPUTDIR} -name "erago*_windows_*.exe" | head -n 1 | xargs basename`

# setting for dst

# we extract version from output of built binary.
VERSION=`${OUTPUTDIR}/${ARCHIVE_SRC_LINUX} -version 2>/dev/null`
ARCHIVE_DIR=`absolute_archive_path ${OUTPUTDIR} ${VERSION}`

ARCHIVE_DST_LINUX=${ARCHIVE_DIR}/${ARCHIVE_SRC_LINUX}.tar.gz
ARCHIVE_DST_DARWIN=${ARCHIVE_DIR}/${ARCHIVE_SRC_DARWIN}.tar.gz
ARCHIVE_DST_WINDOWS=${ARCHIVE_DIR}/${ARCHIVE_SRC_WINDOWS//.exe/.zip}

# -----------------------
# do packing
# -----------------------
set -x
mkdir -p ${ARCHIVE_DIR} 
cp -r ${ARCHIVE_MISC} ${OUTPUTDIR}
cd ${OUTPUTDIR} 

if [ -n "${ARCHIVE_SRC_LINUX}" ]; then
  : "packing for linux..." && \
    tar zcf ${ARCHIVE_DST_LINUX} ${ARCHIVE_SRC_LINUX} ${ARCHIVE_MISC}
fi
if [ -n "${ARCHIVE_SRC_DARWIN}" ]; then
  : "packing for darwin..." && \
    tar zcf ${ARCHIVE_DST_DARWIN} ${ARCHIVE_SRC_DARWIN} ${ARCHIVE_MISC}
fi
if [ -n "${ARCHIVE_SRC_WINDOWS}" ]; then
  : "packing for windows..." && \
    zip -T ${ARCHIVE_DST_WINDOWS} ${ARCHIVE_SRC_WINDOWS} ${ARCHIVE_MISC} 
fi

cd - # return top 
