#!/bin/bash

# assumes runs from top directory of erago repository.

set -eu -o pipefail

source scripts/common

OUTPUTDIR=$1

docker run --rm -t \
  -v $PWD:$DIR_ON_DOCKER \
  -w $DIR_ON_DOCKER \
  $DOCKER_IMAGE_NAME \
  bash scripts/archive $OUTPUTDIR

#make -f $DIR_ON_DOCKER/Makefile.docker cross-archive
