#!/bin/bash

# assumes runs from top directory of erago repository.

set -eu -o pipefail

source scripts/common

docker build --build-arg GOVARIANTS=$DOCKER_IMAGE_GOVARIANTS -t $DOCKER_IMAGE_NAME_MOBILE -f ./dockerfiles/mobile/Dockerfile .
