#!/bin/bash

# build binary for specifed platform on docker environment.
# assumes runs from top directory of erago repository.

set -eu

source scripts/common

TARGET_ROOT=${DIR_ON_DOCKER}
# BUILD_DOCKER_IMAGE=${DOCKER_IMAGE_NAME}
# latest go feature, can apply to linux and windows, but not darwin
BUILD_DOCKER_IMAGE=$DOCKER_IMAGE_NAME_CROSS

BUILD_TARGET=${1:- linux}

docker run --rm -t \
  -v ${REPO_ROOT}:${TARGET_ROOT} \
  -v ${DOCKER_VOLUME_NAME_GOPKG}:/go/pkg \
  -w ${TARGET_ROOT}/app/cmd \
  $BUILD_DOCKER_IMAGE \
  scripts/gh-action-entrypoint.sh make $BUILD_TARGET
