#!/bin/bash

# repository root
SCRIPTS_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
REPO_ROOT="$( dirname "${SCRIPTS_DIR}" )"

# docker image name to be used for cross build
# golang-cross is not used due to dropped latest go version 
# DOCKER_IMAGE_NAME=golang-cross-archive:1.13.15
DOCKER_IMAGE_NAME_CROSS=erago-cross 

DOCKER_IMAGE_NAME_RELEASE=erago-release

# docker image name to be used for mobile build
DOCKER_IMAGE_NAME_MOBILE=gomobile-bind

# docker volume name to be used for build cache for go build
DOCKER_VOLUME_NAME_GOPKG=erago-build-pkg-cache

# working directory on the docker image
DIR_ON_DOCKER=/home/gopher/erago

# return absolute archive path from output binary path and version string.
function archive_path() {
  local OUTPUT_BIN_DIR=$1
  local VERSION=$2

  local OUTPUT_BIN_PATH=$(cd $(dirname $OUTPUT_BIN_DIR) && pwd)/$(basename $OUTPUT_BIN_DIR)

  echo "$OUTPUT_BIN_PATH/archive/$VERSION"
}

# set no path conversion for windows <-> POSIX filesystem for 
# Git for windows environment, which supplies invalid path to docker.
export MSYS_NO_PATHCONV=1 
