#!/bin/bash

# assumes runs from top directory of erago repository.

set -eu -o pipefail

source scripts/common

OUTPUTDIR=${1:-build}

docker run --rm -t \
  -v $PWD:$DIR_ON_DOCKER \
  -w $DIR_ON_DOCKER \
  $DOCKER_IMAGE_NAME_RELEASE \
  bash scripts/credits -o $OUTPUTDIR