#!/bin/bash

set -eu

source scripts/common

OUTPUTDIR=$REPO_ROOT/build
CROSS_BUILD_DIR=$REPO_ROOT/app/cmd

while getopts o: opt; do
	case "$opt" in
		o)
			OUTPUTDIR="$OPTARG"
			;;
		\?)
			echo "Usage: cross [-o OUTPUTDIR]"
			exit 1
			;;
	esac
done
shift $((OPTIND - 1))

# --------------------------
#  Build & Clean
# --------------------------
mkdir -p $OUTPUTDIR
# absolute path is needed for make with change directory option. 
OUTPUTDIR=`absolute_dir_path $OUTPUTDIR`
OUTPUTDIR=$OUTPUTDIR make -C $CROSS_BUILD_DIR -f Makefile linux
OUTPUTDIR=$OUTPUTDIR make -C $CROSS_BUILD_DIR -f Makefile windows
OUTPUTDIR=$OUTPUTDIR make -C $CROSS_BUILD_DIR -f Makefile windows_cli
# OUTPUTDIR=$OUTPUTDIR make -C $CROSS_BUILD_DIR -f Makefile darwin