#!/bin/bash

# assumes runs from top directory of erago repository.

set -eu -o pipefail

source scripts/common

docker run --rm -t \
  -v $PWD:$DIR_ON_DOCKER \
  -v $DOCKER_VOLUME_NAME_GOPKG:/go/pkg \
  -w $DIR_ON_DOCKER \
  $DOCKER_IMAGE_NAME_CROSS \
  bash scripts/cross -o $DIR_ON_DOCKER/build
