name: Try-Workflow

# Controls when the workflow will run
on:
  push:
    branches-ignore: [ "master" ]
    tags-ignore: [ "v*.*.*" ]
    paths: [".github/actions/**", ".github/workflows/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  try-build:
    uses: ./.github/workflows/build-and-release.yml
